name: Hydrate CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Mantém Node.js 18.x

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Yarn
      run: corepack enable

    - name: Install dependencies
      run: yarn install

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Usa Temurin como distribuidor de Java (alternativa ao AdoptOpenJDK)
        java-version: '17'

    - name: Lint code
      run: yarn lint

    - name: Format code (Prettier)
      run: yarn format

    - name: Run tests
      run: yarn test

    - name: Build Android
      run: |
        cd android
        ./gradlew assembleDebug
